apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: list-topics-task
spec:
  params:
    - name: CLUSTER
      type: string
    - name: NAMESPACE
      type: string
  steps:
    - args:
        - '-c'
        - >-
          mkdir -p /tekton/home/.kube; kubectl config view >
          /tekton/home/.kube/config
      command:
        - /bin/bash
      image: gcr.io/cloud-builders/kubectl
      name: set-kubeconfig
      resources: {}
    - command:
        - "kfk"
        - "topics"
        - "--list"
        - "-c"
        - $(inputs.params.CLUSTER)
        - "-n"
        - $(inputs.params.NAMESPACE)
      image: quay.io/systemcraftsman/strimzi-kafka-cli
      name: list-topics
      resources: {}
